import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Hero from "../components/hero";
import Card from "../components/card";

import { getCoffeeStoresData } from "../services/getCoffeStores";
import { useGeolocation } from "../hooks/useGeolocation";
export default function Home({ coffeStoreData }) {
  const [nearCoffeStores, setNearCoffeStores] = useState([]);
  const { handleGeoLocation, status, latLong } = useGeolocation();
  const isError = status === "error";
  const isSuccess = status === "success";
  const isLoading = status === "loading";
  console.log(nearCoffeStores);
  const handleButtonBannerClick = () => {
    handleGeoLocation();
  };
  useEffect(() => {
    if (latLong) {
      getCoffeeStoresData(latLong, "coffee", 30)
        .then((data) => setNearCoffeStores(data))
        .catch((err) => console.log(err));
    }
  }, [latLong]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heroImage}>
        <Hero />
      </div>
      <main className={styles.main}>
        <Banner
          buttonTitle={isLoading ? "Loading..." : "View stores nearby "}
          handleClick={handleButtonBannerClick}
        />
        {isError && <p>location is not avalaible</p>}
        {nearCoffeStores.length > 0 && (
          <>
            <h2 className={styles.secondTitle}>Near Coffee Stores</h2>
            <div className={styles.cardLayout}>
              {nearCoffeStores.map((coffeStore) => {
                const { id, name, imgUrl } = coffeStore;
                return (
                  <Card
                    key={id}
                    className={styles.card}
                    title={name}
                    img={imgUrl}
                    href={`/coffee-store/${id}`}
                  />
                );
              })}
            </div>
          </>
        )}
        <h2 className={styles.secondTitle}>Madrid Coffe Stores</h2>
        <div className={styles.cardLayout}>
          {coffeStoreData.map((coffeStore) => {
            const { id, name, imgUrl } = coffeStore;
            return (
              <Card
                key={id}
                className={styles.card}
                title={name}
                img={imgUrl}
                href={`/coffee-store/${id}`}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const MadridLatLong = "40.41708874959783%2C-3.702210342724132";
  const querySearch = "cafe";
  const limit = 6;
  const coffeStoreData = await getCoffeeStoresData(
    MadridLatLong,
    querySearch,
    limit
  );

  return {
    props: { coffeStoreData },
  };
}
