import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Hero from "../components/hero";
export default function Home() {
  const handleButtonBannerClick = () => {
    console.log("button banner click");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heroImage}>
        <Hero />
      </div>
      <main className={styles.main}>
        <Banner
          buttonTitle="View stores nearby "
          handleClick={handleButtonBannerClick}
        />
      </main>
      <footer></footer>
    </div>
  );
}
